ngworker/lumberjack

.github/workflows/ci.yml
e2e/protractor.conf.js
package.json

```
[ ] Bugfix
[ ] Feature
[ x ] CI related changes
```
It is not running any check on PR
Run build, lint, and test checks on PR or master push ( Add CI )
```
[ ] Yes
[ x ] No
```

chore: 🤖 add ci

---

projects/ngworker/lumberjack/package.json
projects/ngworker/lumberjack/tsconfig.lib.json

```
[ x ] Bugfix
[ ] Feature
```
Missing Author form package.json
```
[ ] Yes
[ ] No
```

fix: 🐛 readme and publish info

---

projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http.driver.ts
src/app/app.component.spec.ts
tsconfig.base.json

```
[ x ] Bugfix
[ ] Feature
```
Strict mode is not activated and there are related issues.
Strict mode is active and related bugs are fixed.
```
[ ] Yes
[ x ] No
```

fix: 🐛 change to strict mode and fix related errors

---

CODE_OF_CONDUCT.md

```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Netanel contact is kept from `@ngneat/lib` template
Netanel email was replace with Nacho Vazquez email.
```
[ ] Yes
[ x ] No
```

docs: ✏️ replace netanel's contact with nachos' in CODE_OF_CONDUCT

---

README.md

Replace README ngneat badge with an ngworker one.
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
README includes a badge for ngneat
ngneat badge has been replaced with a ngworker one.
```
[ ] Yes
[ x ] No
```

docs: ✏️ change ngneat badge with ngworker

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Specator v5 used for tests.
Spectator v6 used for tests.
```
[ ] Yes
[x] No
```

chore: update Spectator to v6

---

.github/workflows/ci.yml
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
angular.json
e2e/tsconfig.json
karma.conf.js
package.json
projects/ngworker/lumberjack/README.md
projects/ngworker/lumberjack/console-driver/src/console-driver.module.spec.ts
projects/ngworker/lumberjack/http-driver/package.json
projects/ngworker/lumberjack/http-driver/src/http-driver-root.module.spec.ts
projects/ngworker/lumberjack/http-driver/src/http-driver.module.spec.ts
projects/ngworker/lumberjack/package.json
projects/ngworker/lumberjack/src/lib/lumberjack.module.spec.ts
projects/ngworker/lumberjack/src/lib/lumberjack.service.isolated.spec.ts
projects/ngworker/lumberjack/src/lib/lumberjack.service.ts
projects/ngworker/lumberjack/tests/expect-ng-module-to-be-guarded.ts
projects/ngworker/lumberjack/tests/index.ts
projects/ngworker/lumberjack/tests/resolve-dependency.ts
src/app/app.component.html
src/app/app.component.spec.ts
src/environments/environment.prod.ts
tsconfig.base.json

- this change should allow testing the lib source code with different
angular versions
Lumberjack is being tested over the current angular version (10.0.x)
Lumberjack is tested over different version of Angular (8.0.x, 9.0.x, 10.0.x)

chore: 🤖 add angular-versions-action to ci pipeline

---

.github/workflows/ci.yml
README.md

```
[ ] Bugfix
[ ] Feature
[ x ] Refactoring (no functional changes, no api changes)
[ x ] Build related changes
[ x ] Documentation content changes
```
The repository has been migrated from using `master` branch to the new default `main` branch.
However, some docs have not been updated and the **CI** is still based on master
Docs are updated to refer to `main` and **CI** uses `main` as the trunk branch.
```
[ ] Yes
[ x ] No …
```

refactor: 💡 move from master branch to main

---

.github/workflows/ci.yml
libs/ngworker/lumberjack/console-driver/src/console-driver-root.module.ts
libs/ngworker/lumberjack/http-driver/src/http-driver-root.module.ts
libs/ngworker/lumberjack/src/lib/lumberjack-root.module.ts
libs/ngworker/lumberjack/src/lib/lumberjack.module.ts
package.json
tsconfig.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
[ x ] CI related changes
```
`Lumberjack` host application is being built and test using `Lumberjack` library sources instead of build bundles. This is a poor compatibility test since is not being tested in the same way it would be used by npm clients.
CI process includes a step before building and testing the app where the path to the library is modified to look at the dist folder.
Issue …

chore: 🤖 use lumberjack library builds for compatibility tests

---

README.md

```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
A badge and a new section promoting wallaby.js is added to the README.md
```
[ ] Yes
[ x ] No
```

docs: ✏️ add wallabyjs badge and README section to project

---

libs/internal/test-util/src/lib/logs/log-creators.ts
libs/internal/test-util/src/lib/noop-driver/noop.driver.ts
libs/internal/test-util/src/lib/spy-driver/spy.driver.ts
libs/ngworker/lumberjack/console-driver/src/console.driver.ts
libs/ngworker/lumberjack/http-driver/src/http.driver.ts
libs/ngworker/lumberjack/src/lib/log-drivers/log-driver.ts
libs/ngworker/lumberjack/src/lib/lumberjack-log-levels.ts
libs/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
libs/ngworker/lumberjack/src/lib/lumberjack.service.ts

```
[ ] Bugfix
[x] Feature
```
1. No Critical log level.
1. No Trace log level.
1. Critical log level added.
1. Trace log level added.
```
[ ] Yes
[x] No
```

feat: add Critical and Trace log levels

---

.github/workflows/ci.yml

```
[ ] Bugfix
[ ] Feature
[ x ] Build related changes
```
CI is running using only some of the possible Angular versions supported by the `angular-versions-action`
CI runs using all possible Angular version supported by the `angular-versions-action`
```
[ ] Yes
[ x ] No
```

chore: 🤖 run ci with all posible inputs of angular-versions

---

apps/lumberjack-app/src/app/log-types/error-logs/app.component.log.ts
apps/lumberjack-app/src/app/log-types/error-logs/index.ts
apps/lumberjack-app/src/app/log-types/info-logs/app.component.log.ts
apps/lumberjack-app/src/app/log-types/info-logs/index.ts

```
[ ] Bugfix
[ ] Feature
```
v1-style logs are in the app project.
v1-style logs are removed from the app project.
```
[ ] Yes
[x] No
```

docs: remove v1 artifacts from app

---

.github/workflows/ci.yml
apps/lumberjack-app/src/app/app-logger.service.ts
libs/ngworker/lumberjack/src/lib/lumberjack-logger.service.spec.ts
libs/ngworker/lumberjack/src/lib/lumberjack-logger.service.ts
package.json

```
[x] Bugfix
[ ] Feature
```
We forgot to add `LumberjackLogger#createCriticalLogger` and `LumberjackLogger#createTraceLogger`.
`LumberjackLogger#createCriticalLogger` and `LumberjackLogger#createTraceLogger` are implemented.
```
[ ] Yes
[x] No
```
Added *Update Chrome* step to the `e2e` job to fix the CI pipeline.

fix: add Critical and Trace to LumberjackLogger

---

README.md
apps/lumberjack-app-e2e/src/app.e2e-spec.ts
apps/lumberjack-app/src/app/app-logger.service.ts

```
[ ] Bugfix
[ ] Feature
```
Docs are outdated and no longer represent the current implementation.
Docs are updated and in sync with `Lumberjack` v2
```
[ ] Yes
[x] No
```

docs: ✏️ update Readme to reflect the new changes in the library

---

angular.json
libs/ngworker/lumberjack/package.json
libs/ngworker/lumberjack/tsconfig.lib.json
libs/ngworker/lumberjack/tsconfig.lib.prod.json

```
[ ] Bugfix
[ ] Feature
```
- Remove deprecated `extractCss` setting.
- Add package description.
- Published as version `2.0.0-beta.1`, tagged as `next`.
- Adjust publish config to prevent accidental releases.
- Set `compilerOptions#declarationMap` to `true` in library development build.
- Enable Ivy in library development build.
```
[ ] Yes
[x] No
```

chore: synchronize configurations with Angular 11 defaults

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(readme): update examples to include module imports

---

.github/workflows/ci.yml

```
[ ] Bugfix
[ ] Feature
```
We're using the version 2 beta of `actions/setup-node` in our CI workflow.
Use the version 2 stable of `actions/setup-node` in our CI workflow.
```
[ ] Yes
[x] No
```

chore: use actions/setup-node stable

---

README.md
apps/lumberjack-app/src/app/app.component.spec.ts
libs/ngworker/lumberjack/src/lib/logging/lumberjack.service.spec.ts
package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Remove test dependency.
```
We're still using Spectator in one test.
Remove Spectator and rewrite the test using it.
```
[ ] Yes
[x] No
```
- Update All Contributors count badge to `4`.

test: remove Spectator

---

apps/lumberjack-app-e2e/src/app.e2e-spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Code smells in `lumbrejack-app-e2e`.
No code smells in `lumbrejack-app-e2e`.
```
[ ] Yes
[x] No
```

test: e2e perfume

---

README.md

```
[ ] Bugfix
[ ] Feature
```
There is no reference to the BLS episode in the docs.
A reference to the BLS episode of Lumberjack v2 was added to the docs.
```
[ ] Yes
[x] No
```

docs: ✏️ add reference to bls walkthrough video

---

sonar-project.properties

```
[ ] Bugfix
[ ] Feature
```
SonarCloud reports *Version not provided*.
SonarCloud reports *Version 2.x* which is used to track code quality over time.
```
[ ] Yes
[x] No
```

ci: add SonarCloud project version

---

.github/workflows/ci.yml
README.md

```
[ ] Bugfix
[ ] Feature
```
No official Angular 11.2.x support.
Proven Angular 11.2.x support.
```
[ ] Yes
[x] No
```
Increased upper Node.js memory limit to 6GB in the CI workflow.

ci: prove Angular 11.2.x support

---

.github/workflows/ci.yml

```
[ ] Bugfix
[ ] Feature
```
Using `ngworker/angular-versions-action@v2`.
Using `ngworker/angular-versions-action@v3`.
```
[ ] Yes
[x] No
```

ci: update angular-versions-action

---

README.md

```
[ ] Bugfix
[ ] Feature
```
The community drivers section in the Readme doesn't list the Application Insights Driver.
The community drivers section in the Readme list the Application Insights Driver.
```
[ ] Yes
[x] No
```

docs: ✏️ add application insights driver to the docs

---

.github/workflows/ci.yml

```
[ ] Bugfix
[ ] Feature
```
Using Angular versions action v3.x.
Using Angular versions action v4.x.
```
[ ] Yes
[x] No
```

ci: update Angular versions action

---

.github/workflows/ci.yml

```
[ ] Bugfix
[ ] Feature
```
Merge CI run some times fails because of network issues. We can't rerun a merge run on `main`.
We can manually trigger a CI run on all branches with the push of a button on GitHub.
```
[ ] Yes
[x] No
```
Example of failed run: https://github.com/ngworker/lumberjack/actions/runs/886937791.

ci: add manual trigger for CI workflow

---

README.md

```
[ ] Bugfix
[ ] Feature
```
Currently the link http driver readme goes to a page not found.
Updated the http driver link in the main readme to point to the http driver readme in libs.
```
[ ] Yes
[x] No
```
Authored by @SergeyCherman.
Closes #90.

docs: fix http driver readme link

---

.github/workflows/ci.yml
package.json

schematics test command was not needed as schematics test cases are being handled by "test:lib"
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

ci: removed unused schmatics test command

---

.github/FUNDING.yml
libs/ngworker/lumberjack/package.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Funding
```
No funding described.
Add individual GitHub Sponsors profiles for @santoshyadavdev and @LayZeeDK.
```
[ ] Yes
[x] No
```

docs: add individual GitHub Sponsors profiles

---

CHANGELOG.md
packages/ngworker/lumberjack/package.json

```
[ ] Bugfix
[ ] Feature
```
- v2.0.3 is the `latest` stable release
- v14.0.0-beta.1 is the `next` release
- v14.0.0 is the `latest` stable release
- v14.0.0 is the `next` release
```
[ ] Yes
[x] No
```

chore: release v14.0.0

---

.github/FUNDING.yml

```
[ ] Bugfix
[ ] Feature
```
Nacho Vazquez is not part of the repository Funding program because he wasn't eligible as a GitHub Sponsors program member.
Nacho Vazquez is part of the repository Funding program since it is now part of the GitHub Sponsors program.
```
[ ] Yes
[x] No
```

docs: add NachoVazquez to funding program

---

README.md
packages/ngworker/lumberjack/package.json

```
[ ] Bugfix
[ ] Feature
```
The project package.json doesn't contain the necessary metadata that npm would read. Additionally, the logo is local and therefore not accessible on npm.
We have included on the package.json the following metadata:
- description
- homepage
- license
- repository
- keywords
- contributors
- bugs
The lumberjack logo was moved to a CDN.
```
[ ] Yes
[x] No
```

chore: add project metadata to package.json

---

packages/ngworker/lumberjack/CHANGELOG.md

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
The Changelog has some format issues
The Changelog format issues are fixed
```
[ ] Yes
[x] No
```

fix: format issues

---

README.md

```
[ ] Bugfix
[ ] Feature
```
The documentation is using the Angular Discord server as the home of Lumberjack Discussions.
The documentation offers a link to the NgWorker Discord server as the howe of Lumberjack
```
[ ] Yes
[x] No
```

docs: replace angular discord server on docs with ngworker discord

---

packages/ngworker/lumberjack/package.json

```
[x] Bugfix
[ ] Feature
```
Lumberjack 15 doesn't support Angular version 16 in its peer dependencies.
Closes: #170 
Lumberjack 15 added support for versions of Angular greater than 15
```
[ ] Yes
[x] No
```

fix: add support for version 16 of Angular

---

packages/ngworker/lumberjack/project.json

```
[ ] Bugfix
[ ] Feature
```
We are not pushing the tags and commits after creating the changelog which causes an error on the GitHub release post actions
We push always to GitHub

fix: pushing the tags and commits is necessary

---

packages/ngworker/lumberjack/package.json
packages/ngworker/lumberjack/project.json

```
[ ] Bugfix
[ ] Feature
```
`@angular/platform-browser` is marked as an optional peer dependency in the published `package.json` file.
Issue Number: #170
`@angular/platform-browser` is not marked as a peer dependency in the published `package.json` file.
```
[ ] Yes
[x] No
```
Reverts #174.

chore: remove `@angular/platform-browser` dependency

---

packages/docs/lumberjack-docs-app/docs/best-practices.md

```
[ ] Bugfix
[ ] Feature
```
The final code example in the best practices section was cut out and incomplete.
The final code example in the best practices section (LumberjackLogFactory) is restored and complete.
```
[ ] Yes
[x] No
```

docs: fix final section on best practices

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.github/workflows/release.yml

```
[ ] Bugfix
[ ] Feature
```
- `actions/checkout@v3`
- `actions/configure-pages@v2`
- `actions/deploy-pages@v1`
- `actions/setup-node@v3`
- `actions/upload-pages-artifact@v1`
- `nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0`
- `nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0`
- `nrwl/nx-set-shas@v3`
- `sonarsource/sonarcloud-github-action@v2.0.0`
- `actions/checkout@v4`
- `actions/configure-pages@v4`
- `actions/deploy-pages@v4`
- …

ci: update GitHub Actions

---

packages/docs/lumberjack-docs-app/src/pages/index.js

```
[x] Bugfix
[ ] Feature
```
We are validating the Feature component props on the docs which is causing Sonar lint issues.
We are validating the components props to fix the Sonar lint issues.
```
[ ] Yes
[x] No
```

fix: sonar lint issues on Docusaurus

---

package.json
packages/ngworker/lumberjack/project.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Closes: #198 
Update ngx-deploy-npm to 8.0.0.
```
[ ] Yes
[x] No
```
Original PR by @dianjuar 
More information about the changes and their motivation can be found on this [blog post](https://dev.to/dianjuar/whats-coming-to-ngx-deploy-npm-v8-23gn)

build: migrate to ngx-deploy-npm v8

---

packages/docs/lumberjack-docs-app/blog/announcing-lumberjack-v17.md

```
[ ] Bugfix
[ ] Feature
```
We are ready to lunch but we haven't written the release notes for version 17
Closes: #193 
The release notes for version 17 are ready to be published.
```
[ ] Yes
[x] No
```

docs: add lumberjack 17 release notes

---

package.json
packages/ngworker/lumberjack/package.json
yarn.lock

```
[x] Bugfix
[ ] Feature
```
The release process is failing.
We have upgrade the `@jscutlery/semver` version to align with our Nx version
```
[ ] Yes
[x] No
```

fix: release workflow

---

.github/workflows/ci.yml
.github/workflows/release.yml

```
[ ] Bugfix
[ ] Feature
```
Every time we merge a PR the docs are automatically deployed.
Docs are deployed only when a manual release is triggered
```
[ ] Yes
[x] No
```

ci: move the publishing of the docs to the release pipeline to sync the package with the docs

---

packages/docs/lumberjack-docs-app/blog/announcing-lumberjack-v19.md
packages/docs/lumberjack-docs-app/docs/compatibility.md
packages/docs/lumberjack-docs-app/docs/log-drivers/log-drivers.md

```
[ ] Bugfix
[ ] Feature
```
- Update the docs to reflect the new changes
- Write an announcement blog post

docs: update the docs and create a new announcement blog
