ngworker/lumberjack

projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts, projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http.driver.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Performance improvements
```
Sending a log wagon to the server triggers change detection for the Angular application even though it will not affect the UI state in any way.
HTTP calls made by the `HttpDriver` are run outside of the Angular zone.
```
[ ] Yes
[x] No
```
I'm unsure what to do about the docs using `HttpDriver` as an example. This and other PRs @NachoVazquez and I discussed are going to change this class a lot. …
=> perf: run HttpDriver outside of NgZone

projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http.driver.ts
```
[x] Bugfix
[ ] Feature
```
1. An HTTP call is only made when using `HttpDriver#logInfo`.
1. An observable is not returned from the private `HttpDriver#log` method until the log wagon is full.
1. An HTTP call is only made when using all `HttpDriver#log*` methods.
1. An observable is always returned from the private `HttpDriver#log` method.
```
[x] Yes
[ ] No
```
This is technically a breaking change as the public API of `HttpDriver` log methods …
=> fix: send log wagon from all log methods

projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http.driver.ts, projects/ngworker/lumberjack/src/lib/log-drivers/log-driver.ts, src/index.html
```
[ x ] Bugfix
[ ] Feature
```
log-* methods from `LogDriver` interface can return `Observable` and `Promise`. This behavior is not desired since the `LumberjackService` cannot determine how to handle different scenarios.
Make log-* just to return void.
```
[ x ] Yes
[ ] No
```
Any third party logger returning an observable or a promise from its log-* methods will suffer from …
=> fix: 🐛 make log signature not to support promise or observable

projects/ngworker/lumberjack/src/lib/log-drivers/console-driver/console-driver.module.spec.ts, projects/ngworker/lumberjack/src/lib/log-drivers/console-driver/console-driver.module.ts
```
[x] Bugfix
[ ] Feature
```
An empty object is used as the default `LogDriverConfig` when no configuration is passed to the `ConsoleDriverModule.forRoot` method. An empty object does not property implement the `LogDriverConfig` interface as a `levels` property is required even though it can be `undefined`.
The `defaultLogDriverConfig` is used when no configuration is passed to the `ConsoleDriverModule.forRoot` method.
```
[ ] Yes
[x] No
```
A test …
=> fix: use valid default config in ConsoleDriverModule.forRoot

projects/ngworker/lumberjack/src/lib/log-drivers/console-driver/console-driver-root.module.ts, projects/ngworker/lumberjack/src/lib/log-drivers/console-driver/console-driver.module.spec.ts, projects/ngworker/lumberjack/src/lib/log-drivers/console-driver/console-driver.module.ts, projects/ngworker/lumberjack/src/lib/log-drivers/console-driver/console.driver.ts
```
[ ] Bugfix
[x] Feature
```
`ConsoleDriverModule` can be imported directly which does not currently make sense.
Consumers must import using `ConsoleDriverModule.forRoot`.
```
[ ] Yes
[x] No
```
Rebase after merging #11 as its commits are included in this one to use the test suite for `ConsoleDriverModule` while refactoring and adding this feature.
=> feat: guard against importing ConsoleDriverModule without forRoot

projects/ngworker/lumberjack/console-driver/src/console-driver.module.spec.ts, projects/ngworker/lumberjack/src/lib/lumberjack-root.module.spec.ts, projects/ngworker/lumberjack/src/lib/lumberjack-root.module.ts, projects/ngworker/lumberjack/src/lib/lumberjack.module.spec.ts, projects/ngworker/lumberjack/src/lib/lumberjack.module.ts, projects/ngworker/lumberjack/src/lib/lumberjack.service.isolated.spec.ts, projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts, projects/ngworker/lumberjack/src/lib/lumberjack.service.ts, yarn.lock
1. `LumberjackModule` can accidentally be imported directly.
1. `LumberjackService` fails when no log drivers are registered.
1. `LumberjackModule` can only be imported using `LumberjackModule.forRoot`.
1. `LumberjackService#log` is a no-op when no log drivers are registered.
Exceptions are thrown if `LumberjackModule` is imported without using `LumberjackModule.forRoot` or is imported more than once using `LumberjackModule.forRoot`.
Fixed a flaky test.
=> feat+fix: add guards to LumberjackModule and prevent failure if no log drivers are registered

README.md, package.json, yarn.lock
- replace GIT_PARAMS (deprecated) with HUSKY_GIT_PARAMS
```
[ ] Bugfix
[ ] Feature
[ x ] CI related changes
```
- `@ngneat/lib` dependency is still present in package.json dependencies even when it is not used.
- Husky is using deprecated $GIT_PARAMS
- `@ngneat/lib` dependency is removed from package.json dependencies
- Husky uses …
=> chore: 🤖 remove @ngneat/lib from dependencies and bring changes

libs/ngworker/lumberjack/console-driver/src/console-driver-root.module.spec.ts, libs/ngworker/lumberjack/console-driver/src/console-driver-root.module.ts, libs/ngworker/lumberjack/http-driver/src/http-driver-root.module.spec.ts, libs/ngworker/lumberjack/http-driver/src/http-driver-root.module.ts, libs/ngworker/lumberjack/src/lib/lumberjack-root.module.spec.ts, libs/ngworker/lumberjack/src/lib/lumberjack-root.module.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
An issue in Angular 9.0 keeps us from marking the injected root module as optional or possibly null.
The injected root module as null to make it more explicit that Angular DI passes null for optional dependencies.
Additionally, tests have been simplified.
```
[ ] Yes
[x] No
```
https://github.com/ngworker/lumberjack/pull/30/files
=> refactor: remove Inject decorator from root module guard

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
```
The `e2e` job is not using the packed library in the `dist` folder.
The `e2e` job uses the packed library in the `dist` folder so that we are actually using the library bundle for our end-to-end tests.
```
[ ] Yes
[x] No
```
=> chore: use dist path in e2e job

apps/lumberjack-app-e2e/src/app.e2e-spec.ts, apps/lumberjack-app/src/app/app-logger.service.ts, apps/lumberjack-app/src/app/app.component.ts, libs/internal/test-util/src/index.ts, libs/internal/test-util/src/lib/logs/log-creators.ts, libs/ngworker/lumberjack/src/index.ts, libs/ngworker/lumberjack/src/lib/configs/default-log.config.ts, libs/ngworker/lumberjack/src/lib/configs/index.ts, libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts, libs/ngworker/lumberjack/src/lib/log-creator.ts, libs/ngworker/lumberjack/src/lib/log-types/debug-logs/index.ts, libs/ngworker/lumberjack/src/lib/log-types/error-logs/index.ts, libs/ngworker/lumberjack/src/lib/log-types/index.ts, libs/ngworker/lumberjack/src/lib/log-types/info-logs/index.ts, libs/ngworker/lumberjack/src/lib/log-types/lumberjack-logger.service.ts, libs/ngworker/lumberjack/src/lib/log-types/warning-logs/index.ts, libs/ngworker/lumberjack/src/lib/lumberjack-log.ts, libs/ngworker/lumberjack/src/lib/lumberjack-logger.service.spec.ts, libs/ngworker/lumberjack/src/lib/lumberjack-logger.service.ts, libs/ngworker/lumberjack/src/lib/lumberjack.module.spec.ts, libs/ngworker/lumberjack/src/lib/lumberjack.module.ts, libs/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts, libs/ngworker/lumberjack/src/lib/time/index.ts, libs/ngworker/lumberjack/src/lib/time/lumberjack-time.service.spec.ts, libs/ngworker/lumberjack/src/lib/time/lumberjack-time.service.ts
```
[ ] Bugfix
[x] Feature
```
1. Timestamps are created at the time of writing the log to the drivers rather than when the log entry was created.
1. No timestamp property on `LumberjackLog`.
1. Timestamp is created non-deterministically.
1. Log factory functions are exposed.
1. - [x] A timestamp property on the log entry represents when it was created
1. - [x] A `createdAt: number` property is added to `LumberjackLog`.
1. - [x] A …
=> feat: add timestamp to log entries

README.md, apps/lumberjack-app/src/app/app-logger.service.ts, libs/internal/test-util/src/lib/logs/log-creators.ts, libs/ngworker/lumberjack/src/lib/configuration/lumberjack.module.spec.ts, libs/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts, libs/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.ts, libs/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.spec.ts, libs/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts, libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.service.spec.ts, libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.service.ts, libs/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts, libs/ngworker/lumberjack/src/lib/logs/lumberjack.log.ts
BREAKING CHANGE: LumberjackLog property context was renamed to scope
```
[ ] Bugfix
[x] Feature
```
`LumberjackLog` uses context to denote the origin or scope of an instance log.
`LumberjackLog` renames context property to scope.
Scope is a more suitable name for the intent of the property and now context can be used in the future for different purposes like holding correlation ids.
```
[x] Yes
[ ] No
```
Any client application of custom driver must …
=> feat: 🎸 rename LumberjackLog property context to scope

libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.spec.ts, libs/ngworker/lumberjack/src/lib/formatting/format-log-driver-error.spec.ts, libs/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts, libs/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.spec.ts, libs/ngworker/lumberjack/src/lib/logging/scoped-lumberjack-logger.service.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Test refactoring
```
`LumberjackLogBuilder` is used in a range of tests. The test must pass it `LumberjackTimeService` and the order of parameters is not apparent.
Most tests using `LumberjackLogBuilder` are refactored to using `LumberjackLogFactory.
```
[ ] Yes
[x] No
```
`ScopedLumberjackLogger` test suite:
- Add parameterized loggers.
- Prevent side effects from logging.
=> test: simplify tests by using LumberjackLogFactory

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
```
Local TypeScript path mappings are not deleted in the `schematics-e2e` CI job. Uncertainty about which package it's using. It has to use the package from the build artifact.
Local TypeScript path mappings are deleted in the `schematics-e2e` CI job. It's definitely using the package from the build artifact.
```
[ ] Yes
[x] No
```
=> ci: add delete-path-alias steps for schematics-e2e job

libs/internal/test-util/src/index.ts, libs/ngworker/lumberjack/console-driver/src/configuration-api.spec.ts, libs/ngworker/lumberjack/console-driver/src/index.ts, libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.ts, libs/ngworker/lumberjack/http-driver/src/configuration-api.spec.ts, libs/ngworker/lumberjack/http-driver/src/index.ts, libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver-root.module.ts, libs/ngworker/lumberjack/src/configuration-api.spec.ts, libs/ngworker/lumberjack/src/index.ts, libs/ngworker/lumberjack/src/lib/configuration/lumberjack-root.module.ts
```
[x] Bugfix
[ ] Feature
```
Root Angular modules such as `LumberjackRootModule` are not exposed in the public APIs. This causes compilation errors in some development environments, for example:
- Certain versions of Nx 11.0.x
- When using Angular Linker (requires Angular CLI >=11.1 and a Lumberjack bundle with partial Ivy compilation)
The following Angular modules are exposed in the public APIs:
- `LumberjackRootModule` (`@ngworker/lumberjack`)
- …
=> fix: export root Angular modules

libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
[The SonarCloud gods are angry](https://sonarcloud.io/project/issues?id=ngworker_lumberjack&open=AXjx4aW2bw9bT6FFaPqS&resolved=false&types=CODE_SMELL) that we're using a deprecated signature of `Observable#subscribe`.
Hopefully, this will please the SonarCloud gods.
```
[ ] Yes
[x] No
```
=> refactor(http-driver): use preferred subscribe signature internally

libs/ngworker/lumberjack/tsconfig.lib.json
```
[ ] Bugfix
[x] Feature
```
Couldn't find any issue related to this, hence pasting backlog card here. Should I create a new issue first and then link it here?
Issue Number: https://github.com/ngworker/lumberjack/projects/1#card-50958521
As per the migration update guide from [angular](https://angular.io/guide/migration-update-module-and-target-compiler-options):
In TypeScript 3.9, the behavior of the TypeScript compiler controlled by module is the same with both …
=> feat(chore): set module compiler option to es2020

.github/workflows/ci.yml
```
[x] Bugfix
[ ] Feature
```
Sonar is not tracking any files. There is no code coverage at all.
We always generate the reports for lints and test to feed them to sonar.
```
[ ] Yes
[x] No
```
=> fix: always run report commands for sonar

packages/docs/lumberjack-docs-app/docs/usage.md
```
[ ] Bugfix
[ ] Feature
```
Duplicate example in https://ngworker.github.io/lumberjack/docs/usage#using-the-lumberjackservice where both show usage with `inject()`.
Updated the first example to use the constructor for injection.
```
[ ] Yes
[x] No
```
Fixes #163
=> docs: Updated inject example to show constructor usage

.github/actions/setup/action.yml, .github/workflows/release.yml, packages/ngworker/lumberjack/project.json
```
[ ] Bugfix
[ ] Feature
```
Currently, we cannot release new versions of Lumberjack using the `release` Github Action because we haven't correctly configure the NPM and Github access tokens
We can now automatically release to NPM and GitHub using the `release` Github Action.
=> chore: fix the permission to enable automatic releases

packages/ngworker/lumberjack/package.json, packages/ngworker/lumberjack/project.json
```
[ ] Bugfix
[ ] Feature
```
`@angular/platform-browser` is being added automatically as a peer dependency to the package.json on the build but is not treated manually.
Closes: #170 
We manually set `@angular/platform-browser` as an optional peerDependency on the package.json.
```
[ ] Yes
[x] No
```
=> fix: manually set @angular/platform-browser as optional peerDependency

packages/ngworker/lumberjack/package.json
```
[ ] Bugfix
[ ] Feature
```
RxJS version is fixed at version `7.5.0`, which makes it incompatible with the newest version of Angular.
RxJS peerDependency is set to support versions between `>= 7.5.0` and `< 8.0.0`
```
[ ] Yes
[x] No
```
=> fix: make rxjs version dynamic to support newest versions of Angular

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
```
We are using `sonarsource/sonarcloud-github-action` v1.7 and pull requests are unable to pass because of a missing SonarCloud report. This version uses an old version of Java no longer supported by SonarCloud.
We are using `sonarsource/sonarcloud-github-action` v2.0.0
```
[ ] Yes
[x] No
```
No breaking changes between v1.7 and v2.0.0 according to their GitHub Releases.
=> ci: update to `sonarsource/sonarcloud-github-action` v2.0.0

packages/ngworker/lumberjack/package.json
This reverts commit 1b718535b72196a845f4601c089ce5e318229b59.
```
[ ] Bugfix
[ ] Feature
```
- Lumberjack 15.0.2-15.0.4 has *official* support for Angular >=15.0.1 (including all major Angular versions after 15)
Issue Number: #170
- Lumberjack 15.x has *official* support for Angular ^15.0.1 (only Angular major version 15)
```
[x] Yes
[ ] No
```
Yes, but it is reverting a mistake released in Lumberjack 15.0.2 (#171)
=> revert "fix: add support for version 16 of Angular"

packages/docs/lumberjack-docs-app/docs/log-drivers/http-driver.md, packages/docs/lumberjack-docs-app/docs/log-drivers/log-drivers.md, packages/internal/test-util/src/lib/error-throwing-driver/error-throwing.driver.spec.ts, packages/internal/test-util/src/lib/logs/driver-log-creators.ts, packages/internal/test-util/src/lib/object-driver/object.driver.spec.ts, packages/internal/test-util/src/lib/spy-driver/spy.driver.spec.ts, packages/ngworker/lumberjack/http-driver/README.md, packages/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts, packages/ngworker/lumberjack/src/index.ts, packages/ngworker/lumberjack/src/lib/configuration/lumberjack-log-driver.config.ts, packages/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts, packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts, packages/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.spec.ts, packages/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts, packages/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts, packages/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.ts, packages/ngworker/lumberjack/src/lib/logging/lumberjack-logger.service.ts, packages/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts, packages/ngworker/lumberjack/src/lib/logging/scoped-lumberjack-logger.service.ts, packages/ngworker/lumberjack/src/lib/logs/lumberjack-config-levels.ts, packages/ngworker/lumberjack/src/lib/logs/lumberjack-level.ts, packages/ngworker/lumberjack/src/lib/logs/lumberjack-log-level.ts, packages/ngworker/lumberjack/src/lib/logs/lumberjack.log.ts, packages/ngworker/lumberjack/src/logs-api.spec.ts
```
[ ] Bugfix
[x] Feature
```
Our log levels are represented using TypeScript enums. 
Fixes #192 
We added support for literal unions for our log levels and deprecated the enums.
```
[x] Yes
[ ] No
```
BREAKING CHANGES: enums levels are deprecated and will be removed on version 19.
=> feat!: add support for string literals and deprecate enums

packages/ngworker/lumberjack/package.json
```
[x] Bugfix
[ ] Feature
```
We didn't update the Lumberjack peer dependencies when upgrading to Angular 16
We use the proper peer dependencies for Lumberjack and Angular 16
```
[ ] Yes
[x] No
```
=> fix: lumberjack, angular peer dependency versions

packages/docs/lumberjack-docs-app/blog/announcing-lumberjack-v17.md, packages/docs/lumberjack-docs-app/blog/announcing-lumberjack-v18.md
```
[ ] Bugfix
[ ] Feature
```
We haven't write the docs for Lumberjack 18
We have a new blog post announcing Lumberjack 18.
```
[ ] Yes
[x] No
```
=> docs: write release notes for lumberjack 18
